<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_HOY</name>
   <tag></tag>
   <elementGuidId>f6a9dbc5-6530-47e7-91ef-d45a02305b18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu-list > li[name=&quot;cat-fechas&quot;] > a.dropdown-toggle.menu.menu-sinpleca</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//ul[@id='menu-list']/li/a)[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d2ec409f-e278-4bed-a196-22b99fc0246a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://agenda.eltucumano.com/hoy</value>
      <webElementGuid>c8684bf9-f1e4-4a8b-9507-a36c584b72f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-toggle menu menu-sinpleca</value>
      <webElementGuid>6a6963a1-b75e-4900-91c2-d167d486981f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HOY</value>
      <webElementGuid>e5a7d77e-3137-4fff-8f56-b9f0f9ed7ae6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menubar&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;top-bar-menu&quot;]/nav[@id=&quot;mainmenu&quot;]/ul[@id=&quot;menu-list&quot;]/li[@class=&quot;menu-actualidad mega-cat-dropdown seccion-link cat-fechas&quot;]/a[@class=&quot;dropdown-toggle menu menu-sinpleca&quot;]</value>
      <webElementGuid>5989aa75-ada0-4eee-9827-9a151122d9dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//ul[@id='menu-list']/li/a)[6]</value>
      <webElementGuid>8dd26938-31a3-44a2-b208-a75bae1a1030</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'HOY')])[2]</value>
      <webElementGuid>f977caa1-5b75-4ac7-a0dd-40fc9071eee7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Variedades'])[2]/following::a[1]</value>
      <webElementGuid>eb8f41b3-3388-4583-bcd3-60b6c7c909ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Arte'])[2]/following::a[2]</value>
      <webElementGuid>06e81fe8-4e81-46b4-bf02-f60ecb03209a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MAÑANA'])[2]/preceding::a[1]</value>
      <webElementGuid>30fac04c-d1b7-4d64-8fdb-db342ccae5dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FINDE'])[2]/preceding::a[2]</value>
      <webElementGuid>6d902f4c-b5d8-4f9b-bb6d-c4538beb1fbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://agenda.eltucumano.com/hoy')])[2]</value>
      <webElementGuid>99a112ba-1dd4-4709-af8b-561253f5b0f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/nav/ul/li/a</value>
      <webElementGuid>9e870d7a-2917-43a4-913f-32bb3780e6c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://agenda.eltucumano.com/hoy' and (text() = 'HOY' or . = 'HOY')]</value>
      <webElementGuid>7c667e0e-e939-433f-9b9c-18f13c5a2b30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
